######################################################################
# Automatically generated by qmake (2.01a) Sa. Aug 20 14:27:07 2016
######################################################################

TEMPLATE = app
TARGET = psi-gui
DEPENDPATH += .
INCLUDEPATH += .

FORMS = window.ui

target.path = /usr/bin/
INSTALLS += target

# Input
HEADERS += PSI_MainWindow.h PSI_SubWindows.h
SOURCES += main.cpp PSI_MainWindow.cpp PSI_SubWindows.cpp
